version: "3.8"

x-common-variables: &common-variables
  DOCKER_RUNNING: "true"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app
    restart: always
    logging:
      driver: "local"
    volumes:
      - type: volume
        source: public-content
        target: /var/www/nmebious/static
        volume:
          nocopy: true
      - type: volume
        source: error-pages
        target: /var/www/nmebious/error-pages
    environment:
      <<: *common-variables
      MAX_FILE_SIZE: ${MAX_FILE_SIZE}
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    restart: always
    logging:
      driver: "local"
    environment:
      <<: *common-variables
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - db
    ports:
      - "4005:4005"
      - "8080:8080"
      - "12345:12345"
    restart: always
    logging:
      driver: "local"
    volumes:
      - quicklisp:/root/quicklisp
      - public-content:/usr/src/app/public
      - error-pages:/usr/src/app/templates/error-pages
      - type: bind
        source: ./src/config.lisp
        target: /usr/src/app/src/config.lisp
    env_file:
      - ./.env
    environment:
      - DB_HOST=db

volumes:
  quicklisp:
  public-content:
  error-pages:
  dbdata:
